"""initial schema

Revision ID: 5b65ec3886ba
Revises: 
Create Date: 2026-08-07 16:39:46.424376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b65ec3886ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=320), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('employee_count_range', sa.String(length=32), nullable=True),
    sa.Column('hq_city', sa.String(length=120), nullable=True),
    sa.Column('hq_country', sa.String(length=120), nullable=True),
    sa.Column('registry_number', sa.String(length=64), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('unverified', 'claimed', 'verified', 'flagged', 'merged', 'removed', name='entity_status'), server_default='unverified', nullable=False),
    sa.Column('merged_into_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index('ix_companies_name_trgm', 'companies', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('seeker', 'employer', 'moderator', 'admin', name='user_role'), server_default='seeker', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('oauth_google_sub', sa.String(length=255), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_google_sub')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('entity_claims',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.Enum('dns_txt', 'email_domain', name='claim_method'), nullable=False),
    sa.Column('verification_token', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='claim_status'), server_default='pending', nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_claims_company_id'), 'entity_claims', ['company_id'], unique=False)
    op.create_index(op.f('ix_entity_claims_user_id'), 'entity_claims', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link_url', sa.String(length=2048), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('recruiters',
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('photo_url', sa.String(length=2048), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_created_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('unverified', 'claimed', 'verified', 'flagged', 'merged', 'removed', name='entity_status'), server_default='unverified', nullable=False),
    sa.Column('merged_into_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merged_into_id'], ['recruiters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_url')
    )
    op.create_index(op.f('ix_recruiters_company_id'), 'recruiters', ['company_id'], unique=False)
    op.create_index(op.f('ix_recruiters_email'), 'recruiters', ['email'], unique=False)
    op.create_index(op.f('ix_recruiters_full_name'), 'recruiters', ['full_name'], unique=False)
    op.create_index('ix_recruiters_full_name_trgm', 'recruiters', ['full_name'], unique=False, postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('subject_type', sa.Enum('company', 'recruiter', 'job_posting', name='subject_type'), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('reporter_user_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('advance_fee', 'fake_job_posting', 'impersonation', 'data_harvesting', 'pyramid_scheme', 'interview_scam', 'payment_scam', 'other', name='report_category'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'under_review', 'confirmed', 'rejected', 'appealed', name='report_status'), server_default='pending', nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('appeal_text', sa.Text(), nullable=True),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_reports_pending', 'reports', ['status'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('ix_reports_reporter_user_id'), 'reports', ['reporter_user_id'], unique=False)
    op.create_index(op.f('ix_reports_subject_id'), 'reports', ['subject_id'], unique=False)
    op.create_table('reviews',
    sa.Column('subject_type', sa.Enum('company', 'recruiter', 'job_posting', name='subject_type'), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=True),
    sa.Column('rating_communication', sa.Integer(), nullable=False),
    sa.Column('rating_process_transparency', sa.Integer(), nullable=False),
    sa.Column('rating_offer_accuracy', sa.Integer(), nullable=False),
    sa.Column('rating_professionalism', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('verified_interaction', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('helpful_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unhelpful_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_reviewer_user_id'), 'reviews', ['reviewer_user_id'], unique=False)
    op.create_index(op.f('ix_reviews_subject_id'), 'reviews', ['subject_id'], unique=False)
    op.create_table('scoring_configs',
    sa.Column('version', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_configs_version'), 'scoring_configs', ['version'], unique=True)
    op.create_table('job_postings',
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('recruiter_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('location_city', sa.String(length=120), nullable=True),
    sa.Column('location_country', sa.String(length=120), nullable=True),
    sa.Column('employment_type', sa.String(length=32), nullable=True),
    sa.Column('required_experience', sa.String(length=32), nullable=True),
    sa.Column('required_education', sa.String(length=32), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=True),
    sa.Column('telecommuting', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_company_logo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_questions', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('status', sa.Enum('unverified', 'claimed', 'verified', 'flagged', 'merged', 'removed', name='entity_status'), server_default='unverified', nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_company_id'), 'job_postings', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_postings_content_hash'), 'job_postings', ['content_hash'], unique=False)
    op.create_index('ix_job_postings_embedding_hnsw', 'job_postings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_job_postings_recruiter_id'), 'job_postings', ['recruiter_id'], unique=False)
    op.create_index(op.f('ix_job_postings_source_url'), 'job_postings', ['source_url'], unique=False)
    op.create_index(op.f('ix_job_postings_title'), 'job_postings', ['title'], unique=False)
    op.create_index('ix_job_postings_title_trgm', 'job_postings', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('report_evidence',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sa.String(length=2048), nullable=False),
    sa.Column('file_type', sa.String(length=120), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_evidence_report_id'), 'report_evidence', ['report_id'], unique=False)
    op.create_table('review_votes',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_id', name='uq_review_vote_user')
    )
    op.create_index(op.f('ix_review_votes_review_id'), 'review_votes', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_votes_user_id'), 'review_votes', ['user_id'], unique=False)
    op.create_table('verifications',
    sa.Column('subject_type', sa.Enum('company', 'recruiter', 'job_posting', name='subject_type'), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('band', sa.Enum('unrated', 'high_risk', 'caution', 'trusted', name='trust_band'), nullable=False),
    sa.Column('sub_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'resolving', 'fetching', 'analysing', 'scoring', 'done', 'failed', name='verification_status'), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('hard_override_reason', sa.String(length=255), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['config_version'], ['scoring_configs.version'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verifications_signals_gin', 'verifications', ['signals'], unique=False, postgresql_using='gin', postgresql_ops={'signals': 'jsonb_path_ops'})
    op.create_index('ix_verifications_subject_computed_at', 'verifications', ['subject_type', 'subject_id', 'computed_at'], unique=False)
    op.create_index(op.f('ix_verifications_subject_id'), 'verifications', ['subject_id'], unique=False)
    op.create_table('verification_signals',
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('sub_score_code', sa.Enum('identity', 'company_legitimacy', 'content_risk', 'link_safety', 'community_signal', name='sub_score_code'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='signal_severity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_signals_code', 'verification_signals', ['code'], unique=False)
    op.create_index(op.f('ix_verification_signals_verification_id'), 'verification_signals', ['verification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_signals_verification_id'), table_name='verification_signals')
    op.drop_index('ix_verification_signals_code', table_name='verification_signals')
    op.drop_table('verification_signals')
    op.drop_index(op.f('ix_verifications_subject_id'), table_name='verifications')
    op.drop_index('ix_verifications_subject_computed_at', table_name='verifications')
    op.drop_index('ix_verifications_signals_gin', table_name='verifications', postgresql_using='gin', postgresql_ops={'signals': 'jsonb_path_ops'})
    op.drop_table('verifications')
    op.drop_index(op.f('ix_review_votes_user_id'), table_name='review_votes')
    op.drop_index(op.f('ix_review_votes_review_id'), table_name='review_votes')
    op.drop_table('review_votes')
    op.drop_index(op.f('ix_report_evidence_report_id'), table_name='report_evidence')
    op.drop_table('report_evidence')
    op.drop_index('ix_job_postings_title_trgm', table_name='job_postings', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_job_postings_title'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_source_url'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_recruiter_id'), table_name='job_postings')
    op.drop_index('ix_job_postings_embedding_hnsw', table_name='job_postings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_job_postings_content_hash'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_company_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_scoring_configs_version'), table_name='scoring_configs')
    op.drop_table('scoring_configs')
    op.drop_index(op.f('ix_reviews_subject_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_user_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reports_subject_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_user_id'), table_name='reports')
    op.drop_index('ix_reports_pending', table_name='reports', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('reports')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_recruiters_full_name_trgm', table_name='recruiters', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_recruiters_full_name'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_email'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_company_id'), table_name='recruiters')
    op.drop_table('recruiters')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_entity_claims_user_id'), table_name='entity_claims')
    op.drop_index(op.f('ix_entity_claims_company_id'), table_name='entity_claims')
    op.drop_table('entity_claims')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index('ix_companies_name_trgm', table_name='companies', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###

    # Alembic autogenerate does not track native enum types shared across
    # multiple tables for cleanup, so drop them explicitly once every
    # column referencing them is gone.
    for enum_name in (
        'entity_status',
        'claim_method',
        'claim_status',
        'user_role',
        'subject_type',
        'report_category',
        'report_status',
        'trust_band',
        'verification_status',
        'sub_score_code',
        'signal_severity',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
